# Meta Data for SEO

## Homepage
title = "El Acantilado"
titleSeparator = "-"
titleAddition = "El Acantilado"
description = "Videogames. Programming. Linux."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = [""]
ogLocale = "es_ES"
domainTLD = "el-acantilado.com/"
titleHome = "El Acantilado"

## Twitter Cards
twitterSite = "@el_acantilado_"
twitterCreator = "@el_acantilado_"

## JSON-LD
# schemaType = "Person"
schemaType = "ElAcantilado"
schemaName = "Wiki"
schemaAuthor = "El Acantilado"
schemaAuthorTwitter = "https://twitter.com/el_acantilado_"
schemaAuthorGitHub = "https://github.com/el-acantilado"
schemaLocale = "es-ES"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/el_acantilado_"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/h-enk/acantilado"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Nuestro <a href=\"https://github.com/el-acantilado\">código es libre</a>. Los contenidos bajo licencia <a rel=\"license\" href=\"http://creativecommons.org/licenses/by/4.0/\">CC BY</a>."

# Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/h-enk/doks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = ['blog','docs']
  searchSectionsIndex = ['blog','docs']
  darkMode = false
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
